### ISSUE TITLE
What is the difference between the coverage files?

### ISSUE THREAD

**Issue by KeelyDulmage** [milesjor/VAULT#4]
Sorry, me again.  What is supposed to be the difference between coverage.3plus.txt and all.coverage.3plus.length.txt?  While at first glance they appeared to be different, after sorting and performing a diff they turned out to be exactly the same.  I was hoping to use these files to throw out low coverage groups but am not entirely sure what I'm looking at.

Thank you!

**Comment by milesjor** [comment]
Hi, the ./snp/coverage.3plus.txt and ./snp/summary/all.coverage.3plus.length.txt are indeed the same file. As you can see in the analysis folder of individual UMI groups, there are {UMI}.coverage.3plus.txt and {UMI}.coverage.txt files. The ./snp/coverage.3plus.txt is generated by combining all {UMI}.coverage.3plus.txt files;

The ./snp/summary/all.coverage.3plus.length.txt is generated by re-analyzing the {UMI}.coverage.txt file as below:
```
cat  {UMI}.coverage.txt | awk 'BEGIN{n=0}{if($3>=3)n+=1}END{print "'$name'",n}' >> {path}/snp/summary/all.coverage.3plus.length.txt
```
so that the two files are redundant, I will probably remove one in the next version.

Just a kind reminder, discarding low coverage groups can omit those UMI groups with large deletions. You may check ./snp/all_sv_from_perfect_umi.filtered.0.5.vcf first to see if there are any large deletions in your data. The files with "all" prefix mean that they are from all UMI groups in ./snp/perfect_umi folder. The files with "pass" prefix mean they are from "--group_filter" passed UMI groups, which is shown in ./snp/pass.group.lst

**Comment by KeelyDulmage** [comment]
Thank you once again for your thorough explanation!

Ah, I will have to check to make sure I'm not throwing out any deletions, that is a good point.
